### ISSUE TITLE
Will it work on 7.4.x?

### ISSUE THREAD

**Issue by wiruzman** [leekelleher/umbraco-export-sqlce#1]

**Comment by leekelleher** [comment]
I haven't tried it myself. Would you like to test it out?

**Comment by wiruzman** [comment]
I'm afraid to do it :)

Med venlig hilsen / Best regards,
Mehmet Karahan

2016-06-28 21:49 GMT+02:00 Lee Kelleher notifications@github.com:

**Comment by leekelleher** [comment]
The project page reports compatibility for v7.2.x, so my assumption would be it's fine in v7.4.x.

https://our.umbraco.org/projects/backoffice-extensions/export-sql-server-compact/

In a worse case scenario the dashboard wouldn't load, it won't corrupt your database. Then you can always uninstall it.

**Comment by leekelleher** [comment]
Closing issue, as I'm archiving this GitHub repo.
